#!/usr/bin/expect

set python [lindex $argv 0]
set managepy [lindex $argv 1]
set username [lindex $argv 2]
set password [lindex $argv 3]

if { $python == "" || $managepy == "" || $username == "" || $password == ""} {
  puts "Usage: <path_to_manage_py> <username> <password>\n"
  exit 1
}

spawn $python $managepy createsuperuser --username $username

expect "Email address:"
send "\r"

expect "Password"
send "$password\r"

expect "Password (again):"
send "$password\r"

expect "Bypass password validation and create user anyway?" {
    send "y\r"
    interact
}

